Dto validation
Oleksandr-Radovets/BookAPI pull request #2
Opened 2023-10-18 07:21 UTC by Oleksandr-Radovets

2023-10-19 14:25 UTC, Rommelua requested changes
task is:
Add CustomGlobalExceptionHandler class
Add meaningful validation for existing DTO classes

remove all staff connected to another task.
Maybe spring data PR was not merged to main?

2023-10-19 14:25 UTC, Rommelua commented on pom.xml
> +            <version>8.0.0.Final</version>
delete it and use 
spring-boot-starter-validation

2023-10-19 14:25 UTC, Rommelua commented on src/main/java/com/example/bookapi/dto/BookSearchParametersDto.java
> +public record BookSearchParametersDto(String[] author, String[] title) {
task is:
Add CustomGlobalExceptionHandler class
Add meaningful validation for existing DTO classes

Why this PR contains BookSearchParametersDto?

2023-10-21 10:44 UTC, kerrrusha approved these changes

2023-10-21 10:44 UTC, kerrrusha commented on src/main/java/com/example/bookapi/controller/BookController.java
> +
redundant blank line

2023-10-21 10:44 UTC, kerrrusha commented on src/main/java/com/example/bookapi/controller/BookController.java
> +
redundant blank line

2023-10-21 10:44 UTC, kerrrusha commented on src/main/java/com/example/bookapi/repository/BookRepository.java
> +
redundant blank line

2025-05-23 19:35 UTC, merged